### PR TITLE
Updated about.html to make more sense

### PR DESCRIPTION
**Pull request by MDxWARRIORxOP**
Updated about.html to make more sense, removed the "show more" button and commented-out most of the code, and replaced the footer with the normal index.html footer

### CODE REVIEW

**Comment by MDxWARRIORxOP** [comment]
its... basically empty now, you can add more to it

**Review by Thisisniceygy — COMMENTED** [review]
Nice one king! I'll merge it when I'm back at my pc. Win 11 updates suck 😅

**Comment by TheAlienDoctor** [comment]
Dw nicey I got you broski 😎

**Comment by MDxWARRIORxOP** [comment]
thanks niceygy and alien!

**Pull request merged**
