### PR TITLE
Update downloads.html

### PR DESCRIPTION
**Pull request by parv66**
uh hey am new to github and also if u see the changes i tried to make, yep thats your fix :D

### CODE REVIEW

**Comment by parv66** [comment]
idk wtf is a pull request aaaaaaaaa

**Comment by parv66** [comment]
am sorry idk what am doing i tried to help

**Comment by TheAlienDoctor** [comment]
That will work once we have uploaded the css onto our web server, so this will stay open until the css is added to the web server
Thanks for you help :)

**Comment by TheAlienDoctor** [comment]
This fix would require us to have all of our css files on the web server, which would mean our development workflow would be slow when trying to update any css/js. As well as this, we have found a new workaround that uses the <base> tag.
Thanks for your help anyway thought! :)

**Pull request closed without merging**
